server:
  port: 8080

spring:
  application:
    name: wallet-app
  profiles:
    active: dev # Default profile

# Basic placeholder - configure DB, JPA, Security etc. here or in profile-specific files
logging:
  level:
    root: INFO
    org.springframework.beans.factory: DEBUG # See bean creation/wiring logs
    org.springframework.boot.autoconfigure: DEBUG # See auto-configuration reports
    org.springframework.orm.jpa: DEBUG    # See JPA setup logs
    org.springframework.data.jpa: DEBUG   # See Spring Data JPA logs
    com.example.wallet: DEBUG
    org.hibernate: DEBUG                

# Example placeholder for JWT config
app:
  jwt:
    secret: your-very-secure-and-long-secret-key-32-bytes-or-more # MUST NOT BE EMPTY OR DEFAULT
    access-token-expiration-ms: 3600000   # e.g., 1 hour
    refresh-token-expiration-ms: 604800000 # e.g., 7 days

# Springdoc OpenAPI basic config
springdoc:
  api-docs:
    path: /api-docs
  swagger-ui:
    path: /swagger-ui.html

---
spring:
  config:
    activate:
      on-profile: dev

# Dev specific config (e.g., H2 console, debug logging)

---
spring:
  config:
    activate:
      on-profile: prod

# Prod specific config (e.g., real DB connection from env vars)
---
spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/walletdb # <<< CHECK THIS LINE EXISTS AND IS CORRECT
    username: walletuser                         # <<< CHECK THIS LINE
    password: changeme_in_prod_and_local_env              # <<< CHECK THIS LINE (Replace with actual password)
    driver-class-name: org.postgresql.Driver       # <<< Optional but good practice

  # Other dev properties like jpa, flyway, logging...
  jpa:
    hibernate:
      ddl-auto: update # Or validate
    show-sql: true
    # ... etc ...

  flyway:
    enabled: true
    locations: classpath:db/migration